apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-api
  labels:
    app: simple-node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node-api
  template:
    metadata:
      labels:
        app: simple-node-api
    spec:
      containers:
      - name: simple-node-api
        image: public.ecr.aws/REDACTED/REDACTED:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-node-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-node-api
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: simple-node-api