service: aurora-sls-test

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:PROFILE, 'default'}
  region: ${env:REGION, 'eu-west-1'}
  stage: ${env:ENV, 'dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rds:*
        - secretsmanager:*
      Resource: "*" # Open permissions for example sake

plugins:
  - serverless-offline

functions:
  - ${file(./serverless/functions.yml)}

resources:
    - ${file(./serverless/vpc.yml)}
    - ${file(./serverless/rds.yml)}